pipeline:
  build:
    image: node:latest
    commands:
      - npm install
      - npm run lint
  publish:
    image: node:latest
    commands:
      - npm install --global release-it
      - np patch --yolo --no-cleanup
    when:
      branch: master
  publish_gh_pages:
    image: plugins/gh-pages
    secrets: [ github_username, github_password ]
    pages_directory: ./
    when:
      branch: master