pipeline:
  build:
    image: node:latest
    commands:
      - npm install
      - npm run lint
  publish:
    image: node:latest
    commands:
      - npm install -g np npm-cli-login
      - npm-cli-login -u "${npm_username}" -p "${npm_password}" -e "${npm_email}"
      - np patch --yolo --no-cleanup
    when:
      branch: master
  publish_gh_pages:
    image: plugins/gh-pages
    secrets: [ github_username, github_password ]
    pages_directory: ./
    when:
      branch: master