pipeline:
  build:
    image: node:latest
    commands:
      - npm install
      - npm run lint
  npm_auth:
    image: robertstettner/drone-npm-auth
    secrets: [ npm_username, npm_password, npm_email ]
    when:
      branch: master
  publish:
    image: node:latest
    commands:
      - node version.js
      - npm publish
    when:
      branch: master