language: node_js
node_js:
  - "7"

cache: yarn

before_install:
  - npm install -g np release-it npm-cli-login
  - npm-cli-login -u $NPM_USERNAME -p $NPM_PASSWORD -e $NPM_EMAIL

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: publish
      script: release-it patch -n
#        - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG_publish
#        - cd $TRAVIS_REPO_SLUG_publish
#        - git checkout -qf $TRAVIS_COMMIT
#        - np patch --yolo --no-cleanup
      if: type = push AND repo = enteam/firebase-websockets-adapter AND branch = master