language: node_js
node_js:
  - "7"

cache: yarn

before_install:
  - npm-cli-login -u $NPM_USERNAME -p $NPM_PASSWORD -e $NPM_EMAIL

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: publish
      script:
        - node version.js
        - npm publish
      if: type = push AND repo = enteam/firebase-websockets-adapter AND branch = master